### ISSUE TITLE
index

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/MyWebSite#1]
in attesa

**Comment by christian99salerno** [comment]
non era necessario appena ho tempo faccio html

**Comment by christian99salerno** [comment]
Prof ma di tutti i paragrafi in inglese devo leggere tutto oh solo leggere le parti che mi spiegano i tag

**Comment by FabioZTessitore** [comment]
Ci sono paragrafi che non spiegano i tag?

Il 18 feb 2017 5:10 PM, "christian99salerno" <notifications@github.com> ha
scritto:

**Comment by christian99salerno** [comment]
Si all'inizio domanda stupida :)

**Comment by FabioZTessitore** [comment]
manca qualcosa in head

l'intestazione principale della pagina l'hai fatta con h3, perché?

tra gli elementi della lista non sono necessari br

**Comment by christian99salerno** [comment]
il titolo deve essere più grande?

**Comment by FabioZTessitore** [comment]
Non devi pensare a come viene visualizzata la pagina, ma al significato degli elementi

**Comment by christian99salerno** [comment]
io br per esempio l'ho messo perchè mi piaceva lo spazio tra gli elementi della lista

**Comment by christian99salerno** [comment]
quindi devo togliere se non devo pensare all'aspetto <br> e <h3>

**Comment by christian99salerno** [comment]
ci li lascio br e h3 tanto e' per bellezza che fa

**Comment by christian99salerno** [comment]
<meta charset="utf-8"> non l'ho messo perchè non so a che serve

**Comment by FabioZTessitore** [comment]
```html
<!-- indica al browser il set di caratteri utilizzato -->
<meta charset="utf-8">
```

**Comment by FabioZTessitore** [comment]
"ci li lascio br e h3 tanto e' per bellezza che fa"

fa che se vuoi fare a modo tuo puoi continuare da solo. Saluti

**Comment by christian99salerno** [comment]
:(

**Comment by christian99salerno** [comment]
Scusate

**Comment by FabioZTessitore** [comment]
Dai, aggiusta
