### ISSUE TITLE
login

### ISSUE THREAD

**Issue by FabioZTessitore** [christian99salerno/MyWebSite#4]
in attesa

**Comment by FabioZTessitore** [comment]
sempre in attesa

**Comment by christian99salerno** [comment]
Ho messo anche login e prof ma per mettere come fatti le varie lezioni sul nuovo sito a cui mi sono iscritto come bisogna fare?

**Comment by FabioZTessitore** [comment]
c'è un pulsante per ogni pagina

**Comment by FabioZTessitore** [comment]
gli elementi del form devono essere fatti secondo le indicazioni date nell'esercizio

**Comment by christian99salerno** [comment]
ok grazie
va bene login?

**Comment by christian99salerno** [comment]
Infatti è quello che ho fatto

**Comment by christian99salerno** [comment]
è area di testo no campo il commento giusto è questo che ho sbagliato

**Comment by FabioZTessitore** [comment]
sono quasi tutti sbagliati

**Comment by christian99salerno** [comment]
:(

**Comment by christian99salerno** [comment]
sembrava troppo bello per essere vero

**Comment by christian99salerno** [comment]
la prima volta è sempre sbagliato

**Comment by christian99salerno** [comment]
mi dite quelle corrette

**Comment by FabioZTessitore** [comment]
rileggi bene il testo e carica la nuova versione, poi vediamo

**Comment by christian99salerno** [comment]
fatto :)

**Comment by christian99salerno** [comment]
sono stato veloce

**Comment by christian99salerno** [comment]
PS: quando volete e avete tempo mi potete segnare come fatti gli esercizi sul nuovo sito delle lezioni

**Comment by christian99salerno** [comment]
*quando volete e quando avete tempo....

**Comment by FabioZTessitore** [comment]
ok, ora devi aggiungere l'attributo name ai vari elementi (e non solo ...)

**Comment by christian99salerno** [comment]
si ma a cosa serviva mi sono dimenticato poichè se non sbaglio me lo avevate detto

**Comment by FabioZTessitore** [comment]
leggi il tutorial su htmldog

**Comment by christian99salerno** [comment]
non ci capisco molto :(
e l'ho tradotto

**Comment by christian99salerno** [comment]
perchè poi nel tutotial dopo name="" viene value="" a che serve

**Comment by FabioZTessitore** [comment]
inizia dal primo elemento, vediamo come faresti

**Comment by christian99salerno** [comment]
vedete ho caricato

**Comment by FabioZTessitore** [comment]
in età evita di usare un nome con la lettera accentata

genere va bene (sia M che F hanno lo stesso name così formano un gruppo), ma devi mettere value

**Comment by christian99salerno** [comment]
ok vedete se va bene

**Comment by FabioZTessitore** [comment]
togli l'apostrofo ...

aggiungi il value anche al titolo di studio (fai attenzione)

**Comment by christian99salerno** [comment]
ok va bene

**Comment by christian99salerno** [comment]
vedete adesso

**Comment by FabioZTessitore** [comment]
no, ti avevo detto di fare attenzione

**Comment by christian99salerno** [comment]
non capisco a cosa devo fare attenzione

**Comment by FabioZTessitore** [comment]
va bene mettere value alle varie option, ma devi toglierlo a select

**Comment by christian99salerno** [comment]
fatto il misfatto
